DROP TABLE DEPARTMENT;

TRUNCATE TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT ( 
	ID		INT					NOT NULL, 
	NAME	VARCHAR (50)		NOT NULL, 
	CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)
)
;

INSERT INTO DEPARTMENT VALUES (1, 'Managment');
INSERT INTO DEPARTMENT VALUES (2, 'Finance and Accounting');
INSERT INTO DEPARTMENT VALUES (3, 'Marketing and Sales');
INSERT INTO DEPARTMENT VALUES (4, 'Research and Development');
INSERT INTO DEPARTMENT VALUES (5, 'Administration');
