DROP TABLE EMPLOYEE_PROJECT;

TRUNCATE TABLE EMPLOYEE_PROJECT;

CREATE TABLE EMPLOYEE_PROJECT (
	EMPLOYEE_ID	INT	NOT NULL, 
	PROJECT_ID	INT	NOT NULL, 
	CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID), 
	CONSTRAINT FK_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
)
;

INSERT INTO EMPLOYEE_PROJECT (1, 5);
