DROP TABLE HACKERS;

CREATE TABLE HACKERS ( 
	HACKER_ID		INT					NOT NULL, 
	NAME			VARCHAR (20)		NOT NULL, 
	PRIMARY KEY (HACKER_ID)
)
;

WITH RESULT AS (
    SELECT H.HACKER_ID, H.NAME, S.CHALLENGE_ID, MAX(S.SCORE) AS SCORE 
    FROM HACKERS H 
    JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID 
    GROUP BY H.HACKER_ID, H.NAME, S.CHALLENGE_ID 
)
SELECT HACKER_ID, NAME, SUM(SCORE) AS TOTAL_SCORE 
FROM RESULT 
GROUP BY HACKER_ID, NAME 
HAVING SUM(SCORE) > 0 
ORDER BY TOTAL_SCORE DESC, HACKER_ID ASC 
;
