Use Hackerrank;

DROP TABLE OCCUPATIONS;

CREATE TABLE OCCUPATIONS (
	NAME		VARCHAR (20)	NOT NULL, 
	OCCUPATION	VARCHAR (20)	NOT NULL, 
)
;

Exec sp_columns OCCUPATIONS;

/*
NAME
OCCUPATION
*/

INSERT INTO OCCUPATIONS VALUES ('A', 'Doctor');
INSERT INTO OCCUPATIONS VALUES ('B', 'Professor');
INSERT INTO OCCUPATIONS VALUES ('C', 'Singer');
INSERT INTO OCCUPATIONS VALUES ('D', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('E', 'Singer');
INSERT INTO OCCUPATIONS VALUES ('F', 'Doctor');
INSERT INTO OCCUPATIONS VALUES ('G', 'Professor');

SELECT * 
FROM OCCUPATIONS 
;

/*
A	Doctor
B	Professor
C	Singer
D	Actor
E	Singer
F	Doctor
G	Professor
*/

SELECT NAME + '(' + LEFT(OCCUPATION,1) + ')' 
FROM OCCUPATIONS 
ORDER BY NAME
;

/*
A(D)
B(P)
C(S)
D(A)
E(S)
F(D)
G(P)
*/

WITH RESULT AS (
	SELECT COUNT(OCCUPATION) AS OCCUPATION_COUNT, OCCUPATION 
	FROM OCCUPATIONS 
	GROUP BY OCCUPATION 
) 
SELECT 'There are a total of', OCCUPATION_COUNT, LOWER(OCCUPATION) + 's.' 
FROM RESULT 
ORDER BY OCCUPATION_COUNT 
;

/*
There are a total of	1	actors.
There are a total of	2	doctors.
There are a total of	2	professors.
There are a total of	2	singers.
*/

SELECT OCCUPATION, COUNT(OCCUPATION) 
FROM OCCUPATIONS O 
GROUP BY OCCUPATION 
;

/*
Actor	1
Doctor	2
Professor	2
Singer	2
*/

WITH RESULT AS (
	SELECT COUNT(OCCUPATION) AS OCCUPATION_COUNT 
	FROM OCCUPATIONS O 
	GROUP BY OCCUPATION 
)
SELECT MAX(OCCUPATION_COUNT) AS MAX_OCCUPATION_COUNT 
FROM RESULT 
;

/*
2
*/

WITH RESULT1 AS (
	SELECT COUNT(OCCUPATION) AS OCCUPATION_COUNT 
	FROM OCCUPATIONS O 
	GROUP BY OCCUPATION 
), 
RESULT2 AS (
	SELECT MAX(OCCUPATION_COUNT) AS MAX_OCCUPATION_COUNT 
	FROM RESULT1 
)
SELECT MAX_OCCUPATION_COUNT 
FROM RESULT2 
;

/*
2
*/

SELECT * 
FROM OCCUPATIONS 
FOR XML PATH('') 
;

/*
<NAME>A</NAME>
<OCCUPATION>Doctor</OCCUPATION>
<NAME>B</NAME>
<OCCUPATION>Professor</OCCUPATION>
<NAME>C</NAME>
<OCCUPATION>Singer</OCCUPATION>
<NAME>D</NAME>
<OCCUPATION>Actor</OCCUPATION>
<NAME>E</NAME>
<OCCUPATION>Singer</OCCUPATION>
<NAME>F</NAME>
<OCCUPATION>Doctor</OCCUPATION>
<NAME>G</NAME>
<OCCUPATION>Professor</OCCUPATION>
*/

SELECT STUFF (
	(
		SELECT DISTINCT ',' + OCCUPATION 
		FROM OCCUPATIONS 
		FOR XML PATH(''), TYPE
	).value('.', 'NVARCHAR(MAX)') 
	,1,1,''
)
;

/*
Actor,Doctor,Professor,Singer
*/

SELECT DISTINCT OCCUPATION 
FROM OCCUPATIONS 
ORDER BY OCCUPATION 
;

/*
Actor
Doctor
Professor
Singer
*/

SELECT 
	O.NAME, 
	O.OCCUPATION, 
	ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS SEQNUM
FROM OCCUPATIONS O 
;

/*
D	Actor	1
A	Doctor	1
F	Doctor	2
B	Professor	1
G	Professor	2
C	Singer	1
E	Singer	2
*/

SELECT 
	MAX(CASE WHEN OCCUPATION = 'Doctor' THEN NAME END) AS Doctor,
	MAX(CASE WHEN OCCUPATION = 'Professor' THEN NAME END) AS Professor,
	MAX(CASE WHEN OCCUPATION = 'Singer' THEN NAME END) AS Singer,
	MAX(CASE WHEN OCCUPATION = 'Actor' THEN NAME END) AS Actor     
FROM (
	SELECT 
		O.NAME, 
		O.OCCUPATION, 
		ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS SEQNUM
    FROM OCCUPATIONS O
) T
GROUP BY SEQNUM 
ORDER BY SEQNUM 
;

/*
A	B	C	D
F	G	E	NULL
*/
