DROP TABLE PROJECT;

TRUNCATE TABLE PROJECT;

CREATE TABLE PROJECT ( 
	ID		INT					NOT NULL, 
	NAME	VARCHAR (50)		NOT NULL, 
	CONSTRAINT PK_PROJECT PRIMARY KEY (ID)
)
;

INSERT INTO PROJECT VALUES (1, 'Twiddle Thumbs');
INSERT INTO PROJECT VALUES (2, 'Solitaire');
INSERT INTO PROJECT VALUES (3, 'Person on Mars');
