DROP TABLE STATION;

TRUNCATE TABLE STATION;

CREATE TABLE STATION (
	ID		INT             NOT NULL, 
	CITY	VARCHAR (21)    NOT NULL, 
	STATE	VARCHAR (2)     NOT NULL, 
	LAT_N	INT				NOT NULL, 
	LONG_W	INT				NOT NULL, 
	PRIMARY KEY (ID)
)
;

INSERT INTO STATION VALUES (1, 'Austin', 'TX', 97.7431, 30.2672);
INSERT INTO STATION VALUES (2, 'Houston', 'TX', 95.3698, 29.7604);
INSERT INTO STATION VALUES (3, 'Corpus Christi', 'TX', 97.3964, 27.8006);
INSERT INTO STATION VALUES (4, 'Dallas', 'TX', 96.7970, 32.7767);
INSERT INTO STATION VALUES (5, 'Lubbuck', 'TX', 101.8552, 33.5779);

SELECT * FROM STATION;

SELECT CITY, STATE FROM STATION;

SELECT DISTINCT CITY FROM STATION WHERE (ID % 2) = 0;

SELECT (COUNT(CITY)- COUNT(DISTINCT CITY)) FROM STATION;

SELECT LEN(CITY) FROM STATION;
SELECT MIN(LEN(CITY)) FROM STATION;

SELECT TOP 1 CITY, LEN(CITY) 
FROM STATION 
WHERE LEN(CITY) = (SELECT MIN(LEN(CITY)) FROM STATION) 
ORDER BY CITY 
;

SELECT TOP 1 CITY, LEN(CITY) 
FROM STATION 
WHERE LEN(CITY) = (SELECT MAX(LEN(CITY)) FROM STATION)
ORDER BY CITY 
;

SELECT DISTINCT CITY 
FROM STATION 
WHERE LEFT(CITY,1) IN ('A', 'E', 'I', 'O', 'U') 
;

SELECT DISTINCT CITY 
FROM STATION 
WHERE RIGHT(CITY,1) IN ('A', 'E', 'I', 'O', 'U') 
;

SELECT DISTINCT CITY 
FROM STATION 
WHERE LEFT(CITY,1) IN ('A', 'E', 'I', 'O', 'U') 
AND RIGHT(CITY,1) IN ('A', 'E', 'I', 'O', 'U') 
;

SELECT DISTINCT CITY 
FROM STATION 
WHERE LEFT(CITY,1) NOT IN ('A', 'E', 'I', 'O', 'U') 
;

SELECT DISTINCT CITY 
FROM STATION 
WHERE RIGHT(CITY,1) NOT IN ('A', 'E', 'I', 'O', 'U') 
;

SELECT DISTINCT CITY 
FROM STATION 
WHERE LEFT(CITY,1) NOT IN ('A', 'E', 'I', 'O', 'U') 
OR RIGHT(CITY,1) NOT IN ('A', 'E', 'I', 'O', 'U') 
;

SELECT 
    MIN(LAT_N) AS MIN_LAT_N, 
    MIN(LONG_W) AS MIN_LONG_W, 
    MAX(LAT_N) AS MAX_LAT_N, 
    MAX(LONG_W) AS MAX_LONG_W
FROM STATION 
;

WITH RESULT AS (
    SELECT 
        MIN(LAT_N) AS MIN_LAT_N, 
        MIN(LONG_W) AS MIN_LONG_W, 
        MAX(LAT_N) AS MAX_LAT_N, 
        MAX(LONG_W) AS MAX_LONG_W
    FROM STATION 
)
SELECT ROUND(ABS(MAX_LAT_N - MIN_LAT_N) + ABS(MAX_LONG_W - MIN_LONG_W), 4) FROM RESULT 
;

WITH RESULT AS (
    SELECT 
        MIN(LAT_N) AS MIN_LAT_N, 
        MIN(LONG_W) AS MIN_LONG_W, 
        MAX(LAT_N) AS MAX_LAT_N, 
        MAX(LONG_W) AS MAX_LONG_W
    FROM STATION 
)
SELECT 
    FORMAT(SQRT(SQUARE(MAX_LAT_N - MIN_LAT_N) + SQUARE(MAX_LONG_W - MIN_LONG_W)), 'F4') 
FROM RESULT 
;
