Use Hackerrank;

DROP TABLE STUDENT;

CREATE TABLE STUDENT (
	ID		INT             NOT NULL, 
	NAME	VARCHAR (17)    NOT NULL, 
	MARKS	INT				NOT NULL, 
	PRIMARY KEY (ID)
)
;

INSERT INTO STUDENT VALUES (1, 'Ashley', 81);
INSERT INTO STUDENT VALUES (2, 'Samantha', 75);
INSERT INTO STUDENT VALUES (3, 'Julia', 76);
INSERT INTO STUDENT VALUES (4, 'Belvet', 84);

SELECT NAME 
FROM STUDENT 
WHERE MARKS > 75 
ORDER BY RIGHT(NAME,3), ID 
;
